name: CI for Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    name: Backend Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: List Directory Structure
        run: ls -R

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Backend Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "Error installing dependencies from requirements.txt. Ensure the file exists and dependencies are correctly listed."
          pip install pytest  # Ensure pytest is installed

      - name: Verify Installed Python Packages
        run: pip list

      - name: Run Backend Tests
        run: |
          pytest tests/ || echo "Tests failed. Verify the test folder path and the test setup."
